"""
ThreatLens — CVE table migration script
Adds all fields introduced in Phase 3, 4, and 5 that were missing from
the original Phase 2 schema.

SAFE TO RUN MULTIPLE TIMES — skips any column that already exists.

Run from your project root:
    python migrate.py

Or point at a different DB:
    python migrate.py --db path/to/threatlens.sqlite
"""

import sqlite3
import os
import sys
import argparse
from datetime import datetime

# ── Config ────────────────────────────────────────────────────────────────────

DEFAULT_DB = os.path.join("backend", "database", "threatlens.sqlite")

# Each entry: (column_name, sql_type, default_clause)
#
# Phase 3 — NVD ingestion + CISA KEV + scoring
# Phase 4 — Endpoint agent signals
# Phase 5 — AI brain outputs
MIGRATIONS = [
    # ── Phase 3 — risk scoring inputs ─────────────────────────────────────────
    ("cisa_kev",             "INTEGER NOT NULL DEFAULT 0",
     "Boolean: CVE is on the CISA Known Exploited Vulnerabilities list"),

    ("ransomware_use",       "INTEGER NOT NULL DEFAULT 0",
     "Boolean: CVE linked to active ransomware campaigns (from KEV catalog)"),

    ("patch_available",      "INTEGER NOT NULL DEFAULT 0",
     "Boolean: vendor patch exists, parsed from CVE description keywords"),

    ("actively_exploited",   "INTEGER NOT NULL DEFAULT 0",
     "Boolean: active exploitation detected (CISA KEV or OSINT signal)"),

    ("asset_affected",       "INTEGER NOT NULL DEFAULT 0",
     "Boolean: at least one registered asset matches this CVE's products"),

    ("affected_asset_count", "INTEGER NOT NULL DEFAULT 0",
     "Count of registered assets affected by this CVE"),

    # ── Phase 3 — risk score outputs ──────────────────────────────────────────
    ("risk_score",           "REAL NOT NULL DEFAULT 0.0",
     "Composite risk score 0-100 from 9-component formula"),

    ("risk_band",            "TEXT NOT NULL DEFAULT 'LOW'",
     "Risk band: LOW | MEDIUM | HIGH | CRITICAL"),

    # ── Phase 5 — AI brain outputs ────────────────────────────────────────────
    ("ai_summary",           "TEXT",
     "Plain-English analyst summary generated by GPT-4o Analyst Agent"),

    ("mitre_tags",           "TEXT",
     "JSON array of MITRE ATT&CK stage strings e.g. [\"Execution\",\"Persistence\"]"),
]

# ── Helpers ───────────────────────────────────────────────────────────────────

def get_existing_columns(cursor, table="cves"):
    cursor.execute(f"PRAGMA table_info({table})")
    return {row[1] for row in cursor.fetchall()}


def backup_db(db_path):
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = db_path + f".bak_{ts}"
    import shutil
    shutil.copy2(db_path, backup_path)
    return backup_path


def run_migration(db_path, dry_run=False):
    if not os.path.exists(db_path):
        print(f"[ERROR] Database not found: {db_path}")
        sys.exit(1)

    print(f"\nThreatLens CVE Migration")
    print(f"Database : {db_path}")
    print(f"Mode     : {'DRY RUN (no changes written)' if dry_run else 'LIVE'}")
    print(f"{'='*55}")

    if not dry_run:
        backup = backup_db(db_path)
        print(f"Backup   : {backup}\n")

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    existing = get_existing_columns(cursor)
    added = []
    skipped = []

    for col_name, col_def, description in MIGRATIONS:
        if col_name in existing:
            skipped.append(col_name)
            print(f"  [SKIP]  {col_name:<25} already exists")
            continue

        sql = f"ALTER TABLE cves ADD COLUMN {col_name} {col_def}"
        print(f"  [ADD]   {col_name:<25} {col_def}")
        print(f"          # {description}")

        if not dry_run:
            cursor.execute(sql)
            added.append(col_name)
        else:
            added.append(col_name)  # count it for the summary

    if not dry_run:
        conn.commit()

    conn.close()

    print(f"\n{'='*55}")
    print(f"Summary: {len(added)} column(s) added, {len(skipped)} skipped")

    if added:
        print(f"\nColumns added:")
        for c in added:
            print(f"  + {c}")

    if dry_run:
        print("\n[DRY RUN] No changes were written. Re-run without --dry-run to apply.")
    else:
        print("\n[DONE] Migration complete. Restart your FastAPI backend now.")
        print("       Verify with:  python check_schema.py")


# ── Post-migration: backfill risk scores for existing rows ────────────────────

BACKFILL_SQL = """
-- After migration, existing CVE rows have risk_score=0 and risk_band='LOW'.
-- Run this block to recalculate scores using the data already in the DB.
-- NOTE: This is a best-effort backfill using only the columns available.
-- Full recalculation (with EPSS, KEV, etc.) runs automatically on next ingest.

UPDATE cves
SET risk_score = ROUND(
    (COALESCE(cvss_score, 0) / 10.0 * 25)                    -- CVSS component (0-25)
    + (COALESCE(epss_score, 0) * 20)                          -- EPSS component (0-20)
    + (CASE WHEN cisa_kev = 1 THEN 15 ELSE 0 END)             -- KEV bonus
    + (CASE WHEN actively_exploited = 1 THEN 10 ELSE 0 END)   -- Exploit signal
    + (CASE WHEN asset_affected = 1 THEN 10 ELSE 0 END)       -- Asset exposure
    + (CASE WHEN ransomware_use = 1 THEN 5 ELSE 0 END)        -- Ransomware signal
    + (CASE WHEN patch_available = 0 THEN 5 ELSE 0 END)       -- No patch penalty
    + (                                                         -- Temporal/recency bonus
        CASE
            WHEN published_date >= date('now', '-1 day')  THEN 10
            WHEN published_date >= date('now', '-3 days') THEN 7
            WHEN published_date >= date('now', '-7 days') THEN 4
            ELSE 0
        END
    ), 2),
risk_band = CASE
    WHEN risk_score >= 86 THEN 'CRITICAL'
    WHEN risk_score >= 61 THEN 'HIGH'
    WHEN risk_score >= 31 THEN 'MEDIUM'
    ELSE 'LOW'
END
WHERE risk_score = 0;
"""

def run_backfill(db_path):
    print(f"\nRunning risk score backfill on existing rows...")
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.execute("SELECT COUNT(*) FROM cves WHERE risk_score = 0")
    count = cursor.fetchone()[0]
    print(f"  Rows with risk_score = 0: {count}")

    if count == 0:
        print("  Nothing to backfill.")
        conn.close()
        return

    # SQLite UPDATE with CASE referencing the just-set column is evaluated row by row
    # Split into two passes for correctness
    cursor.executescript("""
        UPDATE cves
        SET risk_score = ROUND(
            (COALESCE(cvss_score, 0) / 10.0 * 25)
            + (COALESCE(epss_score, 0) * 20)
            + (CASE WHEN cisa_kev = 1 THEN 15 ELSE 0 END)
            + (CASE WHEN actively_exploited = 1 THEN 10 ELSE 0 END)
            + (CASE WHEN asset_affected = 1 THEN 10 ELSE 0 END)
            + (CASE WHEN ransomware_use = 1 THEN 5 ELSE 0 END)
            + (CASE WHEN patch_available = 0 THEN 5 ELSE 0 END)
            + (
                CASE
                    WHEN published_date >= date('now', '-1 day')  THEN 10
                    WHEN published_date >= date('now', '-3 days') THEN 7
                    WHEN published_date >= date('now', '-7 days') THEN 4
                    ELSE 0
                END
            ), 2)
        WHERE risk_score = 0;

        UPDATE cves
        SET risk_band = CASE
            WHEN risk_score >= 86 THEN 'CRITICAL'
            WHEN risk_score >= 61 THEN 'HIGH'
            WHEN risk_score >= 31 THEN 'MEDIUM'
            ELSE 'LOW'
        END;
    """)

    conn.commit()

    cursor.execute("SELECT risk_band, COUNT(*) FROM cves GROUP BY risk_band ORDER BY COUNT(*) DESC")
    rows = cursor.fetchall()
    print("  Backfill complete. Distribution:")
    for band, cnt in rows:
        print(f"    {band:<10} {cnt} CVEs")

    conn.close()


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="ThreatLens CVE migration")
    parser.add_argument("--db",      default=DEFAULT_DB, help="Path to threatlens.sqlite")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing")
    parser.add_argument("--backfill",action="store_true", help="Also backfill risk scores on existing rows")
    args = parser.parse_args()

    run_migration(args.db, dry_run=args.dry_run)

    if args.backfill and not args.dry_run:
        run_backfill(args.db)
